### ISSUE TITLE
Provide more verbose errors on bad certificates

### ISSUE THREAD

**Issue by timothybasanov** [certificate-helper/TLS-Inspector#71]
**Affected Version:**
1.5.3.29.11.0e

**Is this a Test Flight version or the App Store version?**
App Store

**Device and iOS Version:**
iOS 11, iPhone 6

**What steps will reproduce the problem?**
1. Open a url with a known bad certificate chain

**What is the expected output?**
Error message detailing why this certificate chain is not trusted. 

**What do you see instead?**
Generic error message that this cert is not trusted. 

**Please provide any additional information below.**
I want to debug some differences between iOS and macOS certificate validation policies. 
It{s important not to only know that cert is bad, but the reason as well.

**Comment by ecnepsnai** [comment]
Hi @timothybasanov ,

There's limited information we have as to why the certificate isn't trusted, as the trust API in iOS is very limited.

I'll look into what kinds of information I can get from the API to provide better trust failure reasons.

**Comment by ecnepsnai** [comment]
This bug seems to be probably the one big problem with TLS Inspector, that we lack the means to properly check the failure reason when verifying the certificate.

This is due to apple basically telling us exactly nothing when it comes to certificate trust results, and us having to figure it out for ourselves. We can accomplish this, but it may prove to be buggy.

There's two ways we can try this:

1. Using the information we have from the full chain, try to figure out ourselves what went wrong
2. When a certificate isn't trusted, use libssl to attempt to figure out what went wrong.

For number two, the reason we don't use libssl entirely (and still use Apple's socket API) is because Apple does not expose the root CAs to applications. One way we could get around this is by using Mozilla's CA bundle.

I'm leaning more towards option two, since mozilla's CA bundle is well trusted and libssl will (should?) give us more info into a trust failure (since the underlying SSL framework iOS uses is boringSSL).

I'm going to reach out to a trusted member of the TLS community for advice and see what options we can come up with.
