### ISSUE TITLE
Some URL's don't have the TLS Inspector share action available

### ISSUE THREAD

**Issue by fallingrock** [certificate-helper/TLS-Inspector#75]
**Affected Version:** 1.5.3.29.1.1.0e

**Is this a Test Flight version or the App Store version?**
App store

**Device and iOS Version:**
iPhone 6S iOS 11.0.1

**What steps will reproduce the problem?**

1. Browse to https://forums.garmin.com
2. Tap share in safari
3. TLS Inspector shows up
4. Browse to https://static.garmincdn.com/com.garmin.connect/content/images/device-images/vivoactive3.png
5. Tap share in safari
6. TLS Inspector does not show up and is not available as an option

Here is a screen shot of Safari without the TL:S Inspector option
![link-without-tls-inspector](https://user-images.githubusercontent.com/4029821/31237642-2a3651e4-a9bd-11e7-9801-cf73bd5a12b1.PNG)

Here is a screen shot with the TLS inspector option
![link-with-tls-inspector](https://user-images.githubusercontent.com/4029821/31237647-2d294b9a-a9bd-11e7-8904-48430eaff70b.PNG)

**Comment by ecnepsnai** [comment]
Hi @fallingrock 

It looks like this happens whenever you're viewing a image or other media file in Safari as the share sheet changes context from sharing a webpage to sharing the media itself.

We don't register the share action for images or media, since it isn't always possible to get the URL from that image.

I'll do a little investigation into this but it's likely not going to be fixed without making the logic even more spaghetti-like.

As a workaround you can press & hold on a any link or image and select "Share" and can view the certificate that way.
